#define AIRM2M_USB_DEVICE_VENDOR_ID  0x1782
#define AIRM2M_USB_DEVICE_PRODUCT_ID 0x4e00

#define AIRM2M_USB_DEVICE_AT_PPP_INTERFACE_ID 2
#define AIRM2M_USB_DEVICE_AT_PPP2_INTERFACE_ID 3
#define AIRM2M_USB_DEVICE_AP_DIAG_INTERFACE_ID 4
#define AIRM2M_USB_DEVICE_CP_DIAG_INTERFACE_ID 5

char* FindUsbDevice(int device_interface_id);


